version: '3.8'
services:
  angular-app:
    container_name: angular_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8100:80
    volumes:
      - .:/app
      - /app/node_modules
